version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:8080
    environment:
      TELEGRAM_API_ID : *
      TELEGRAM_API_HASH : *
    volumes:
      - /pythontest/data